// Copyright 2026 Abaxx Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * PendingFlowStore — PKCE state validation for OAuth 2.0 + PKCE browser flows.
 *
 * Without state validation, a CSRF attacker can inject a forged authorization code by directing
 * the user's browser to the callback URL with a code they control. The `state` parameter ties
 * each callback to a specific flow this server initiated — unknown state values are rejected
 * before any code exchange.
 *
 * Prevents:
 *   - CSRF attacks: unknown state → rejected (attacker cannot guess the state)
 *   - Replay attacks: state is single-use → deleted after successful consume
 *   - Expired flow reuse: 10-minute TTL on pending flows
 *
 * For multi-server deployments, back this with Redis or a shared keystore so that the server
 * that initiated the flow can validate the callback even if it lands on a different instance.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

interface PendingFlow {
  /** The PKCE code verifier stored for this flow. Validated in consume(). */
  codeVerifier: string;
  /** Unix milliseconds when this flow expires. */
  expiresAt: number;
}

/** Default flow TTL: 10 minutes. Long enough for a human to complete the redirect. */
const DEFAULT_FLOW_TTL_MS = 10 * 60 * 1000;

// ─── PendingFlowStore ─────────────────────────────────────────────────────────

/**
 * Tracks in-flight OAuth flows. One instance per OidcProvider.
 * Enforces: state was generated by this instance, not expired, codeVerifier matches, single-use.
 */
export class PendingFlowStore {
  private flows = new Map<string, PendingFlow>();
  private ttlMs: number;

  constructor(ttlMs = DEFAULT_FLOW_TTL_MS) {
    this.ttlMs = ttlMs;
  }

  /** Register a new flow. Opportunistically purges expired flows on each call. */
  register(state: string, codeVerifier: string): void {
    this.purgeExpired();
    this.flows.set(state, {
      codeVerifier,
      expiresAt: Date.now() + this.ttlMs,
    });
  }

  /**
   * Validate and consume a flow. Throws PendingFlowError on any validation failure.
   * Deletes the flow on success — single-use enforcement.
   */
  consume(state: string, codeVerifier: string): void {
    const flow = this.flows.get(state);
    if (!flow) {
      throw new PendingFlowError(
        'Unknown or already-used OAuth state parameter — possible CSRF attempt or expired flow. ' +
          'Restart the authorization flow.',
      );
    }

    if (Date.now() > flow.expiresAt) {
      this.flows.delete(state);
      throw new PendingFlowError(
        'OAuth authorization flow has expired (10-minute limit). ' +
          'Restart the authorization flow.',
      );
    }

    if (codeVerifier !== flow.codeVerifier) {
      // Do not delete — probing attack. Let the flow expire naturally.
      throw new PendingFlowError(
        'PKCE code verifier mismatch. ' +
          'The codeVerifier passed to exchangeCode() must match the value from buildAuthorizationUrl().',
      );
    }

    this.flows.delete(state);
  }

  /** Remove all expired flows. */
  private purgeExpired(): void {
    const now = Date.now();
    for (const [state, flow] of this.flows) {
      if (now > flow.expiresAt) this.flows.delete(state);
    }
  }
}

// ─── Error Type ───────────────────────────────────────────────────────────────

/** Thrown by PendingFlowStore.consume() on validation failure. */
export class PendingFlowError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PendingFlowError';
  }
}
